language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CXX=g++-5
        - CC=gcc-5       

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CXX=g++-6
        - CC=gcc-6       

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CXX=g++-7
        - CC=gcc-7       

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CXX=g++-8
        - CC=gcc-8       

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CXX=g++-9
        - CC=gcc-9       

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CXX=g++-9
        - CC=gcc-9

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - CXX=g++-10
        - CC=gcc-10  

    - os: freebsd

# Build and steps
script:
  - mkdir build
  - cd build
  - wget https://cmake.org/files/v3.12/cmake-3.12.4.tar.gz
  - tar -xzf cmake-3.12.4.tar.gz
  - cd cmake-3.12.4
  - ./configure
  - make
  - cd ..
  - ./cmake-3.12.4/bin/cmake ..
  - make
  - export OMP_NUM_THREADS=4
  - ./../util/test_script.sh  
